# Generated by Django 5.0.6 on 2024-06-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_about_delete_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='twitter_link',
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='assignments.about')),
            ],
        ),
    ]
